# Generated by Django 2.2 on 2019-04-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('message', models.TextField(default='')),
                ('text', models.CharField(default='', max_length=120)),
                ('background', models.CharField(default='', max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Additional Services',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('site', models.CharField(default='', max_length=250)),
                ('url', models.URLField()),
                ('rate', models.FloatField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='static/img', width_field='width_field')),
                ('width_field', models.IntegerField(default=200)),
                ('height_field', models.IntegerField(default=200)),
            ],
            options={
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('message', models.TextField(default='')),
                ('text', models.CharField(default='', max_length=120)),
                ('background', models.CharField(default='', max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
